name: Call Update .gitignore

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  call-update-gitignore:
    uses: ./.github/workflows/update-gitignore.yaml
    with:
      url_suffix: 'linux,git,zsh,visualstudiocode'
